language: java
sudo: true
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
before_install:
  - chmod +x mvnw

jobs:
  include:
    - stage: build docker image/ login then push to docker hub
      script:
        - docker build -f Dockerfile -t tommymai/eksamenpgr301:eksamenpgr301 .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push tommymai/eksamenpgr301:eksamenpgr301






