language: java
sudo: true
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
before_install:
  - chmod +x mvnw

jobs:
  include:
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - stage: push to docker hub
      script:
        - docker login -u tommymai -p 2372ea1d1e
    - stage: push to docker hub
      script:
        - docker push tommymai/eksamenpgr301:eksamenpgr301






