grafana:
  image: grafana/grafana:6.6
  ports:
    - 3000:3000
  volumes:
    - /var/lib/grafana
  environment:
    GF_SECURITY_ADMIN_PASSWORD: admin
influxdb:
  image: influxdb:1.7.9
  ports:
    - 8086:8086
  volumes:
    - /var/lib/influxdb
  environment:
    INFLUXDB_HTTP_AUTH_ENABLED: "true"
    INFLUXDB_USER: user
    INFLUXDB_USER_PASSWORD: pass
    INFLUXDB_DB: eksamenpgr301
    INFLUXDB_ADMIN_USER: admin
    INFLUXDB_ADMIN_PASSWORD: secret